### ISSUE TITLE
Questions about running the program

### ISSUE THREAD

**Issue by XiaoyuGuo123** [JaesungBae/SCR-CapsNet#1]
Can this program run without noise? Because when the noise is clean, it always has an error.

running  python feature_generation.py
"noise name: clean
save_path: /home/dsp/Desktop/fish/kws/SCR-CapsNet-master/speech_dataset/KWS_feature_saved
mode: fbank
['backward', 'bed', 'bird', 'cat', 'dog', 'down', 'eight', 'five', 'follow', 'forward', 'four', 'go', 'happy', 'house', 'learn', 'left', 'marvin', 'nine', 'no', 'off', 'on', 'one', 'right', 'seven', 'sheila', 'six', 'stop', 'three', 'tree', 'two', 'up', 'visual', 'wow', 'yes', 'zero']
Number of labels: 35
Processing in /home/dsp/Desktop/fish/kws/SCR-CapsNet-master/speech_dataset/Google_Speech_Command/backward
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:193: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "
Traceback (most recent call last):
  File "feature_generation.py", line 298, in <module>
    noise_name=noise_name, noiseSNR=noiseSNR)
  File "feature_generation.py", line 234, in feature_generation
    if label == 30: raise ValueError('wrong') 
ValueError: wrong"
I don't know what happened.
Can you provide a detailed operating instructions if you are convenient?

thanks

**Comment by JaesungBae** [comment]
Hi,
As I know you could also train and test the code only with clean data. In training, I didn't use the noise data.

The error you got is because I only used the labels in Google Speech Command dataset, which is represented in the 'text_to_label' function and you have other labels such as 'backward' or 'visual', etc. 

I think you could add your additional labels to 'text_to_label' function, remove the assertion and run the code. However, since I didn't test the code by adding other labels, so other error could occur.

Thanks.

**Comment by XiaoyuGuo123** [comment]
thanks

**Comment by zfy1416** [comment]
I want to ask a quest about a function----du.pick_mis_recognized
I can't find it in the data_utils.py
I want to know how can I get it.
thanks

**Comment by zfy1416** [comment]
> Can this program run without noise? Because when the noise is clean, it always has an error.
> 
> running python feature_generation.py
> "noise name: clean
> save_path: /home/dsp/Desktop/fish/kws/SCR-CapsNet-master/speech_dataset/KWS_feature_saved
> mode: fbank
> ['backward', 'bed', 'bird', 'cat', 'dog', 'down', 'eight', 'five', 'follow', 'forward', 'four', 'go', 'happy', 'house', 'learn', 'left', 'marvin', 'nine', 'no', 'off', 'on', 'one', 'right', 'seven', 'sheila', 'six', 'stop', 'three', 'tree', 'two', 'up', 'visual', 'wow', 'yes', 'zero']
> Number of labels: 35
> Processing in /home/dsp/Desktop/fish/kws/SCR-CapsNet-master/speech_dataset/Google_Speech_Command/backward
> /usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/data.py:193: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0.
> warnings.warn("Numerical issues were encountered "
> Traceback (most recent call last):
> File "feature_generation.py", line 298, in
> noise_name=noise_name, noiseSNR=noiseSNR)
> File "feature_generation.py", line 234, in feature_generation
> if label == 30: raise ValueError('wrong')
> ValueError: wrong"
> I don't know what happened.
> Can you provide a detailed operating instructions if you are convenient?
> 
> thanks

Can u reply my question that i query author?
thanks
